### ISSUE TITLE
Error in services/BrendaWork -> start

### ISSUE THREAD

**Issue by robksawyer** [robksawyer/brenda-web#11]
```
debug: Running `brenda-work` with arguments:
debug: -c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_drquretesting_job_drqure.conf" -T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame" -s 1 -e 10 push
error: Error: no work, run with -h for usage

  at [object Object].PythonShell.parseError (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:173:17)
  at ChildProcess.<anonymous> (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:80:28)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
 { [Error: no work, run with -h for usage
]
  executable: '/usr/local/bin/python',
  options: [ '-u' ],
  script: 'lib/brenda/brenda-work',
  args: [ '-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_drquretesting_job_drqure.conf" -T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame" -s 1 -e 10 push' ],
  exitCode: 2 }
debug: results: undefined
error: Sending 500 ("Server Error") response:
 Error: no work, run with -h for usage

  at [object Object].PythonShell.parseError (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:173:17)
  at ChildProcess.<anonymous> (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:80:28)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
 { [Error: no work, run with -h for usage
]
  executable: '/usr/local/bin/python',
  options: [ '-u' ],
  script: 'lib/brenda/brenda-work',
  args: [ '-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_drquretesting_job_drqure.conf" -T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame" -s 1 -e 10 push' ],
  exitCode: 2 }
```

According to the [lib/brenda-work](https://github.com/robksawyer/brenda/blob/master/brenda-work) script. The error 

```
#print "OPTS", (opts, args)
    if not args:
        print >>sys.stderr, "no work, run with -h for usage"
        sys.exit(2)
```

appears when the script is run without any arguments.

So it seems that my current method of passing arguments isn't working. Maybe I need to RTFM for [python-shell](https://www.npmjs.com/package/python-shell).

```
var arguments = '-c "' + configFilePath + '" -T "' + taskFilePath + '" -s ' + jobs[0].animation_start_frame + ' -e ' + jobs[0].animation_end_frame + ' push';
sails.log('Running `brenda-work` with arguments: ');
sails.log(arguments);

var options = {
    mode: 'binary',
    pythonPath: '/usr/local/bin/python', /* If installed with 'brew install python' */
    pythonOptions: ['-u'],
    scriptPath: 'lib/brenda/',
    args: [arguments]
};
sails.python.run('brenda-work', options,
    function (err, results) {
        if (err) {
            sails.log.error(err);
            reject(err);
        }
        // results is an array consisting of messages collected during execution
        sails.log('results: %j', results);
        fulfill(results);
    }
);
```

**Comment by robksawyer** [comment]
New error, yay!

```
debug: Running `brenda-work` with arguments:
debug: [ '-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"',
  '-T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame"',
  '-s 1',
  '-e 10',
  'push' ]
error: Error: IOError: [Errno 2] No such file or directory: ' "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"'
  at [object Object].PythonShell.parseError (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:166:17)
  at ChildProcess.<anonymous> (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:80:28)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1067:12)

    ----- Python Traceback -----
    File "lib/brenda/brenda-work", line 121, in <module>
      main()
    File "lib/brenda/brenda-work", line 107, in main
      conf = config.Config(opts.config, 'BRENDA_')
    File "/Users/robsawyer/Brenda/brenda-web/lib/brenda/brenda/config.py", line 31, in __init__
      with open(config_file) as f: { [Error: IOError: [Errno 2] No such file or directory: ' "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"']
  traceback: 'Traceback (most recent call last):\n  File "lib/brenda/brenda-work", line 121, in <module>\n    main()\n  File "lib/brenda/brenda-work", line 107, in main\n    conf = config.Config(opts.config, \'BRENDA_\')\n  File "/Users/robsawyer/Brenda/brenda-web/lib/brenda/brenda/config.py", line 31, in __init__\n    with open(config_file) as f:\nIOError: [Errno 2] No such file or directory: \' "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"\'\n',
  executable: '/usr/local/bin/python',
  options: [ '-u' ],
  script: 'lib/brenda/brenda-work',
  args:
   [ '-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"',
     '-T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame"',
     '-s 1',
     '-e 10',
     'push' ],
  exitCode: 1 }
debug: results: undefined
error: Sending 500 ("Server Error") response:
 Error: IOError: [Errno 2] No such file or directory: ' "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"'
  at [object Object].PythonShell.parseError (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:166:17)
  at ChildProcess.<anonymous> (/Users/robsawyer/Brenda/brenda-web/node_modules/python-shell/index.js:80:28)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1067:12)

    ----- Python Traceback -----
    File "lib/brenda/brenda-work", line 121, in <module>
      main()
    File "lib/brenda/brenda-work", line 107, in main
      conf = config.Config(opts.config, 'BRENDA_')
    File "/Users/robsawyer/Brenda/brenda-web/lib/brenda/brenda/config.py", line 31, in __init__
      with open(config_file) as f: { [Error: IOError: [Errno 2] No such file or directory: ' "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"']
  traceback: 'Traceback (most recent call last):\n  File "lib/brenda/brenda-work", line 121, in <module>\n    main()\n  File "lib/brenda/brenda-work", line 107, in main\n    conf = config.Config(opts.config, \'BRENDA_\')\n  File "/Users/robsawyer/Brenda/brenda-web/lib/brenda/brenda/config.py", line 31, in __init__\n    with open(config_file) as f:\nIOError: [Errno 2] No such file or directory: \' "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"\'\n',
  executable: '/usr/local/bin/python',
  options: [ '-u' ],
  script: 'lib/brenda/brenda-work',
  args:
   [ '-c "/Users/robsawyer/Brenda/brenda-web/jobs/testing_job_wn9w9mtesting_job_wn9w9m.conf"',
     '-T "/Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame"',
     '-s 1',
     '-e 10',
     'push' ],
  exitCode: 1 }
```

**Comment by robksawyer** [comment]
Well the job configuration file clearly exists.

![screen shot 2015-06-09 at 7 48 01 pm](https://cloud.githubusercontent.com/assets/179419/8073928/8802e104-0ee0-11e5-9770-3fa347baee4e.png)

**Comment by robksawyer** [comment]
Tried the command `brenda-work -c /Users/robsawyer/Brenda/brenda-web/jobs/testing_job_jaspgxtesting_job_jaspgx.conf -T /Users/robsawyer/Brenda/brenda-web/lib/brenda/task-scripts/frame -s 1 -e 10 -d push` via the command prompt and received:

```
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 1 -e 1 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 2 -e 2 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 3 -e 3 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 4 -e 4 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 5 -e 5 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 6 -e 6 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 7 -e 7 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 8 -e 8 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 9 -e 9 -j 1 -t 0 -a
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s 10 -e 10 -j 1 -t 0 -a
```

So the actual script seems to be working.

**Comment by robksawyer** [comment]
Ended up just rewriting the brenda-work spot method with the NodeJS Amazon API. See the `start` method in [api/services/BrendaWork.js](https://github.com/robksawyer/brenda-web/blob/master/api/services/BrendaWork.js).

**Comment by xgt001** [comment]
Stumbled with the same thing as well! Thanks for the pointers!

**Comment by robksawyer** [comment]
@xgt001 No prob.
