### ISSUE TITLE
sockets.io is throwing (global.File && obj instanceof File) error

### ISSUE THREAD

**Issue by robksawyer** [robksawyer/brenda-web#23]
```
/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:30
         (global.File && obj instanceof File)
                                        ^
TypeError: Expecting a function in instanceof check, but got #<bound>
  at _hasBinary (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:30:41)
  at hasBinary (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:56:10)
  at Object.socketIOClientCallback (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/lib/socket.js:349:16)
  at MockServerResponse._clientCallback (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/lib/receive-incoming-sails-io-msg.js:217:17)
  at MockClientResponse.<anonymous> (/usr/local/lib/node_modules/sails/lib/router/res.js:72:18)
  at MockClientResponse.emit (events.js:129:20)
  at finishMaybe (_stream_writable.js:484:14)
  at endWritable (_stream_writable.js:493:3)
  at MockClientResponse.Writable.end (_stream_writable.js:459:5)
  at MockServerResponse.onend (_stream_readable.js:505:10)
  at MockServerResponse.g (events.js:199:16)
  at MockServerResponse.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickDomainCallback (node.js:381:11)

```

**Comment by robksawyer** [comment]
Apparently, this is a known issue. It's because I'm using File as a model. Hmm... Maybe I'll rename this Upload
